CREATE DATABASE IF NOT EXISTS pizzeria;

USE pizzeria;

CREATE TABLE IF NOT EXISTS CLIENTS (
    dni CHAR(9) PRIMARY KEY,
    client_name VARCHAR(20),
    client_address VARCHAR(25),
    clieent_phone VARCHAR(9)
);

CREATE TABLE IF NOT EXISTS ORDERS (
    order_id INT AUTO_INCREMENT PRIMARY KEY,
    total_price SMALLINT UNSIGNED,
    order_date DATE NOT NULL DEFAULT (CURRENT_DATE),
    order_state ENUM('Pending', 'Preparation', 'Ready', 'Served/Delivered', 'Cancelled') NOT NULL DEFAULT 'Pending'
);

CREATE TABLE IF NOT EXISTS PIZZAS (
    pizza_id INT AUTO_INCREMENT PRIMARY KEY,
    pizza_name VARCHAR(15),
    base_price TINYINT UNSIGNED
);

CREATE TABLE IF NOT EXISTS MASSES (
    mass_id INT AUTO_INCREMENT PRIMARY KEY,
    mass_name VARCHAR(10),
    mass_price TINYINT UNSIGNED
);

CREATE TABLE IF NOT EXISTS INGREDIENTS (
    ingredient_id INT AUTO_INCREMENT PRIMARY KEY,
    ingredient_name VARCHAR(10),
    ingredient_price TINYINT UNSIGNED,
    ingredient_description VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ALLERGENS (
    allergen_id INT AUTO_INCREMENT PRIMARY KEY,
    allergen_name VARCHAR(10),
    allergen_description VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS INGREDIENT_TYPES (
    ingredient_type_id INT AUTO_INCREMENT PRIMARY KEY,
    ingredient_type_name VARCHAR(10),
    ingredient_type_description VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS MASSES_PIZZAS (
    pizza_id INT,
    FORENIGN KEY (pizza_id) REFERENCES PIZZAS(pizza_id) ON DELETE CASCADE ON UPDATE CASCADE,
    mass_id INT,
    FOREIGN KEY (mass_id) REFERENCES MASSES(mass_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ORDERS_PIZZAS (
    pizza_id INT,
    FOREIGN KEY (pizza_id) REFERENCES PIZZAS(pizza_id) ON DELETE CASCADE ON UPDATE CASCADE,
    order_id INT,
    FOREIGN KEY (order_id) REFERENCES ORDERS(order_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS INGREDIENTS_ALLERGENS (
    ingredient_id INT,
    FOREIGN KEY (ingredient_id) REFERENCES INGREDIENTS(ingredient_id) ON DELETE CASCADE ON UPDATE CASCADE,
    allergen_id INT,
    FOREIGN KEY (allergen_id) REFERENCES ALLERGENS(allergen_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PIZZAS_INGREDIENTS (
    pizza_id INT,
    FOREIGN KEY (pizza_id) REFERENCES PIZZAS(pizza_id) ON DELETE CASCADE ON UPDATE CASCADE,
    ingredient_id INT,
    FOREIGN KEY (ingredient_id) REFERENCES INGREDIENTS(ingredient_id) ON DELETE CASCADE ON UPDATE CASCADE,
    grams_per_ingredient TINYINT UNSIGNED,
    CHECK (grams_per_ingredient BETWEEN 10 and 30)
);

