CREATE DATABASE IF NOT EXISTS taller;

USE taller;

CREATE TABLE IF NOT EXISTS MECANICOS (
    dni CHAR(9) PRIMARY KEY,
    nombre VARCHAR(20),
    edad TINYINT UNSIGNED
);

CREATE TABLE IF NOT EXISTS VEHICULOS (
    matricula CHAR(7) PRIMARY KEY,
    propietario VARCHAR(20),
    marca VARCHAR(20),
    reparado_por CHAR(9) REFERENCES MECANICOS(dni)
);

DESCRIBE MECANICOS;
DESCRIBE VEHICULOS;