CREATE DATABASE IF NOT EXISTS empresa_db;

USE empresa_db;

CREATE TABLE IF NOT EXISTS CLIENTES (
    dni CHAR(9) PRIMARY KEY,
    nom VARCHAR(50),
    direccion VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS PAGOS_PENDIENTES (
    codigo INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    dni CHAR(9),
    importe DOUBLE,
    FOREIGN KEY (dni) REFERENCES CLIENTES(dni) ON DELETE CASCADE ON UPDATE CASCADE
);

DESCRIBE CLIENTES;
DESCRIBE PAGOS_PENDIENTES;

INSERT INTO CLIENTES VALUES ('73849508I', 'Pikachu', 'C/ de la Concordia, 34');
INSERT INTO PAGOS_PENDIENTES (dni, importe) VALUES ('73849508I', 467);
INSERT INTO PAGOS_PENDIENTES (dni, importe) VALUES ('73849508I', 56.7);

SELECT * FROM CLIENTES;
SELECT * FROM PAGOS_PENDIENTES;

DELETE FROM CLIENTES WHERE nom = 'Pikachu';

SELECT * FROM CLIENTES;
SELECT * FROM PAGOS_PENDIENTES;

INSERT INTO CLIENTES VALUES ('73849508I', 'Pikachu', 'C/ de la Concordia, 34');

UPDATE CLIENTES SET dni = '75647389U' WHERE nom = 'Pikachu';

SELECT * FROM CLIENTES;
SELECT * FROM PAGOS_PENDIENTES;