USE pizzeria;

-- Eliminamos las claves foraneas que dependan de claves primarias.

ALTER TABLE ORDERS_PIZZAS DROP FOREIGN KEY orders_pizzas_ibfk_2;
ALTER TABLE PIZZAS_MASSES DROP FOREIGN KEY pizzas_masses_ibfk_1;
ALTER TABLE ORDERS_PIZZAS DROP FOREIGN KEY orders_pizzas_ibfk_1;
ALTER TABLE PIZZAS_INGREDIENTS DROP FOREIGN KEY pizzas_ingredients_ibfk_1;
ALTER TABLE PIZZAS_MASSES DROP FOREIGN KEY pizzas_masses_ibfk_2;
ALTER TABLE INGREDIENTS DROP FOREIGN KEY ingredients_ibfk_1;
ALTER TABLE INGREDIENTS_ALLERGENS DROP FOREIGN KEY ingredients_allergens_ibfk_1;
ALTER TABLE PIZZAS_INGREDIENTS DROP FOREIGN KEY pizzas_ingredients_ibfk_2;
ALTER TABLE INGREDIENTS_ALLERGENS DROP FOREIGN KEY ingredients_allergens_ibfk_2;

-- Eliminamos las claves primarias necesarias.

ALTER TABLE ORDERS DROP PRIMARY KEY;
ALTER TABLE PIZZAS DROP PRIMARY KEY;
ALTER TABLE MASSES DROP PRIMARY KEY;
ALTER TABLE INGREDIENT_TYPES DROP PRIMARY KEY;
ALTER TABLE INGREDIENTS DROP PRIMARY KEY;
ALTER TABLE ALLERGENS DROP PRIMARY KEY;

-- Reestablecemos las claves primarias.

ALTER TABLE ORDERS ADD PRIMARY KEY (order_id);
ALTER TABLE PIZZAS ADD PRIMARY KEY (pizza_id);
ALTER TABLE MASSES ADD PRIMARY KEY (mass_id);
ALTER TABLE INGREDIENT_TYPES ADD PRIMARY KEY (ingredient_type_id);
ALTER TABLE INGREDIENTS ADD PRIMARY KEY (ingredient_id);
ALTER TABLE ALLERGENS ADD PRIMARY KEY (allergen_id);

-- Modificamos las columnas necesarias para que sean AUTO_INCREMENT.

ALTER TABLE ORDERS MODIFY order_id INT AUTO_INCREMENT;
ALTER TABLE PIZZAS MODIFY pizza_id INT AUTO_INCREMENT;
ALTER TABLE MASSES MODIFY mass_id INT AUTO_INCREMENT;
ALTER TABLE INGREDIENT_TYPES MODIFY ingredient_type_id INT AUTO_INCREMENT;
ALTER TABLE INGREDIENTS MODIFY ingredient_id INT AUTO_INCREMENT;
ALTER TABLE ALLERGENS MODIFY allergen_id INT AUTO_INCREMENT;

-- Modificamos las columnas de las claves foraneas independientes para que coincidan los tipos de datos.

ALTER TABLE PIZZAS_MASSES MODIFY pizza_id INT;
ALTER TABLE PIZZAS_MASSES MODIFY mass_id INT;
ALTER TABLE ORDERS_PIZZAS MODIFY pizza_id INT;
ALTER TABLE ORDERS_PIZZAS MODIFY order_id INT;
ALTER TABLE INGREDIENTS_ALLERGENS MODIFY ingredient_id INT;
ALTER TABLE INGREDIENTS_ALLERGENS MODIFY allergen_id INT;
ALTER TABLE PIZZAS_INGREDIENTS MODIFY pizza_id INT;
ALTER TABLE PIZZAS_INGREDIENTS MODIFY ingredient_id INT;
ALTER TABLE INGREDIENTS MODIFY ingredient_type_id INT;


-- Reestablecemos las claves foráneas.

ALTER TABLE ORDERS_PIZZAS ADD CONSTRAINT orders_pizzas_ibfk_2 FOREIGN KEY (order_id) REFERENCES ORDERS(order_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PIZZAS_MASSES ADD CONSTRAINT pizzas_masses_ibfk_1 FOREIGN KEY (pizza_id) REFERENCES PIZZAS(pizza_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ORDERS_PIZZAS ADD CONSTRAINT orders_pizzas_ibfk_1 FOREIGN KEY (pizza_id) REFERENCES PIZZAS(pizza_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PIZZAS_INGREDIENTS ADD CONSTRAINT pizzas_ingredients_ibfk_1 FOREIGN KEY (pizza_id) REFERENCES PIZZAS(pizza_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PIZZAS_MASSES ADD CONSTRAINT pizzas_masses_ibfk_2 FOREIGN KEY (mass_id) REFERENCES MASSES(mass_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE INGREDIENTS ADD CONSTRAINT ingredients_ibfk_1 FOREIGN KEY (ingredient_type_id) REFERENCES INGREDIENT_TYPES(ingredient_type_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE INGREDIENTS_ALLERGENS ADD CONSTRAINT ingredients_allergens_ibfk_1 FOREIGN KEY (ingredient_id) REFERENCES INGREDIENTS(ingredient_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PIZZAS_INGREDIENTS ADD CONSTRAINT pizzas_ingredients_ibfk_2 FOREIGN KEY (ingredient_id) REFERENCES INGREDIENTS(ingredient_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE INGREDIENTS_ALLERGENS ADD CONSTRAINT ingredients_allergens_ibfk_2 FOREIGN KEY (allergen_id) REFERENCES ALLERGENS(allergen_id) ON DELETE CASCADE ON UPDATE CASCADE;

-- Comprobamos que las tablas estan bien creadas.

DESCRIBE CLIENTS;
DESCRIBE ORDERS;
DESCRIBE PIZZAS;
DESCRIBE MASSES;
DESCRIBE ALLERGENS;
DESCRIBE INGREDIENTS;
DESCRIBE INGREDIENT_TYPES;
DESCRIBE ORDERS_PIZZAS;
DESCRIBE PIZZAS_MASSES;
DESCRIBE INGREDIENTS_ALLERGENS;
DESCRIBE PIZZAS_INGREDIENTS;